# Generated by Django 5.2.5 on 2025-09-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='age',
            field=models.SmallIntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=23, max_length=200),
            preserve_default=False,
        ),
    ]
